// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/send-email.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/projects.tsx";
import * as $$0 from "./islands/Cat.tsx";
import * as $$1 from "./islands/ContactForm.tsx";

const manifest = {
  routes: {
    "./routes/api/send-email.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/projects.tsx": $2,
  },
  islands: {
    "./islands/Cat.tsx": $$0,
    "./islands/ContactForm.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
